# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Habib Irani
name: Habib Irani
email: habibirani@txstate.edu
description: >
  PhD Candidate in Computer Science at Texas State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://habibirani.github.io" # the base hostname & protocol for your site

# User settings
username: Habib Irani
user_description: PhD Candidate in Computer Science
user_title: PhD Candidate
email: habibirani@txstate.edu
# twitter_username: 
github_username: habibirani
# gplus_username:  

# Google Scholar ID (get from your scholar URL)
scholar_userid: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=rfwgLzcAAAAJ

# ORCID ID
orcid_id: https://orcid.org/0009-0003-5035-9257

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:path/
  news:
    output: true
    permalink: /news/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"

# Plugin settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Theme
# remote_theme: jekyll/minima